file-upload/file-upload/urls.py
from django.conf.urls import include, url
from django.http import HttpResponseRedirect
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^$', lambda x: HttpResponseRedirect('/upload/')),
    url(r'^upload/', include('fileupload.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file-upload/fileupload/urls.py
from django.conf.urls import url
from fileupload.views import (
        #BasicPlusVersionCreateView,
        EkFileCreateView, EkFileDeleteView, EkFileListView,
        )
from . import views

app_name='fileupload'
urlpatterns = [
    #url(r'^basic/plus/$', BasicPlusVersionCreateView.as_view(), name='upload-basic-plus'),
    url(r'^new/$', EkFileCreateView.as_view(), name='upload-new'),
    url(r'^delete/(?P<pk>\d+)$', EkFileDeleteView.as_view(), name='upload-delete'),
    url(r'^view/$', EkFileListView.as_view(), name='upload-view'),
    url(r'^$',views.index,name='index'),
    url(r'^verify$',views.verify,name='verify'),
    url(r'^transfer/$', views.transfer, name="transfer"),
    url(r'^verify_USB/$', views.verify_USB, name="verifyusb"),
]

file-upload/fileupload/models.py
from django.db import models


class EkFile(models.Model):
    file = models.FileField(upload_to="pictures")
    slug = models.SlugField(max_length=50, blank=True)

    def __str__(self):
        return self.file.name

    @models.permalink
    def get_absolute_url(self):
        return ('upload-new', )

    def save(self, *args, **kwargs):
        self.slug = self.file.name
        super(EkFile, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """delete -- Remove to leave file."""
        self.file.delete(False)
        super(EkFile, self).delete(*args, **kwargs)

file-upload/fileupload/views.py
import json, os, subprocess
import logging

from .USBFinder import attemptMount,transfer_file
from hashlib import sha1
from django.http import HttpResponse,HttpResponseRedirect, JsonResponse
from django.template import Context, loader
from django.shortcuts import render,get_object_or_404
from django.views.generic import CreateView, DeleteView, ListView
from .models import EkFile
from django.contrib.auth.models import User
from .response import JSONResponse, response_mimetype
from .serialize import serialize
from django.urls import reverse

staticFileLoc = '/Programming/Scratch/file-upload-master/file-upload/file-upload/media/'
staticFileLocRoot ='/home/'+'skeletrox'+staticFileLoc


#files_existing=[]
#list_of_files=[]
old_files = []
files = []
total_amount = 0
total_done = 0
count = 0
is_auth = False
optional_flag = False
percentage_done = 0

class NoFilesError(ValueError):
    def __init__ (self, arg = None):
        self.strerror = arg
        self.args = {arg}

def index(request):
    return render(request,'fileupload/LOGIN.html')

def verify(request, optional=False):
    flag='INIT'
    global is_auth, user, password, optional_flag
    if optional:
        optional_flag = True
        usb_checked = attemptMount()
        usb_flag = 'disabled'
        text = 'Please insert USB and refresh   '
        if usb_checked is not None:
            usb_flag = 'active'
            text = 'Click USB Download to download files'
        return render(request, 'fileupload/ekfile_form.html', {'usb_checked': usb_flag, 'text':text})
    try:
        user=User.objects.get(username=request.POST['email'])
        logger = logging.getLogger(__name__)
        password=request.POST['password']
    #_,salt,hashpw=user.password.split('$')
        logger.error(request.POST['email']+","+request.POST['password']+" \n next line")
        logger.error(user.password+", username is "+user.username)
        flag='REAL'
    except User.DoesNotExist:
        flag = 'FAKE'
    if(flag == 'REAL' and user.check_password(password)):
        is_auth = True
        #return HttpResponseRedirect('new/')
        usb_checked = attemptMount()
        usb_flag = 'disabled'
        text = 'Please insert USB and refresh   '
        if usb_checked is not None:
            usb_flag = 'active'
            text = 'Click USB Download to download files'
        return render(request, 'fileupload/ekfile_form.html', {'usb_checked': usb_flag, 'text':text})
    else:
        return render(request,'fileupload/LOGIN.html',{'invalid':'not a valid username or password',})
        
    
    
    
class EkFileCreateView(CreateView):
    model = EkFile
    fields = "__all__"

    def form_valid(self, form):
        
        self.object = form.save()
        print self.object
        files = [serialize(self.object)]
        data = {'files': files}
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        print 'Before you send post request'
        return response

    def form_invalid(self, form):
        data = json.dumps(form.errors)
        return HttpResponse(content=data, status=400, content_type='application/json')


#class BasicPlusVersionCreateView(EkFileCreateView):
 #   template_name_suffix = '_basicplus_form'


class EkFileDeleteView(DeleteView):
    model = EkFile

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        response = JSONResponse(True, mimetype=response_mimetype(request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response


class EkFileListView(ListView):
    model = EkFile
    
    def render_to_response(self, context, **response_kwargs):
        files = [ serialize(p) for p in self.get_queryset() ]
        data = {'files': files}
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response

def verify_USB(request):
    if request.type == 'GET':
        value = attemptMount()
        response_data = 'disabled'
        if value is not None:
            response_data = 'active '
        return JsonResponse({'data':response_data})

def split_dirs(text):
    splitty = text.split('/')
    value = splitty[len(splitty) - 1]
    return value

def transfer(request):
    try:
        if not is_auth:
            return HttpResponse("Please access this URL properly")
            '''
        elif percentage_done == 100:
            template = loader.get_template('fileupload/ekfile_form.html')
            return render(request, 'fileupload/ekfile_form.html', {'usb_checked': 'active', 'text' : 'Insert another USB to download files if you want'})
            '''
        elif request.method == 'GET' or request.method == 'POST':
            global percentage_done
            global total_amount, total_done, count, files, old_files
            files_existing = []
            if request.method == 'GET':
                new_files = attemptMount()
                if new_files is None:
                    return render(request, 'fileupload/ekfile_form.html', {'usb_checked': 'disabled', 'text' : 'You have removed USB, please reinsert and login again'})
                old_files = [fModel.file for fModel in EkFile.objects.all()]
                files = [thing for thing in new_files if split_dirs(thing) not in old_files]
                #old_files.extend(files)
                print '[Z] OldFiles are ' + str(old_files)
                print '[Z] Files are ' + str(files)
                total_done = 0
                total_amount = len(files)
                fileCount = 0
            else:
                fileCount = request.POST.get("file_descriptor", "")
            download_more = True
            print '[Z]################################Length of files = ' + str(len(files)) + '----------------------------------'
            print '[Z]--------------------------------Value of fileCount = ' + str(fileCount) + '----------------------------------'
            print '[Z]--------------------------------Value of totalDone = ' + str(total_done) + '----------------------------------'
            print '[Z]--------------------------------Value of totalAmount = ' + str(total_amount) + '################################'
            '''
            if fileCount is None:
                fileCount = 0
            '''

            file_to_transfer = None
            if len(files) > 0:
                temp_value = 0
                for file in files:
                    if file != 'content.json':
                        try:
                            value = split_dirs(file)
                            #fModel = EkFile(id = count+1, file = str(value))
                            print '[Z]Looking in EkFiles with file ' + value
                            x = EkFile.objects.get(file=str(value))
                            print '[Z]Duplicate found, please ignore ' + value
                            #files.remove(file)
                        except EkFile.DoesNotExist:
                            #x = '@CONST: FILEDOESNOTEXIST'
                            print 'Unique File ' + value + ' Found!'
                            file_size = os.stat(file).st_size
                            value = split_dirs(file)
                            fModel = EkFile(id = temp_value+1, file = str(value))
                            print '[Z]FModelled as ' + str(value)
                            temp_value += 1
                            if fModel not in files_existing:
                                files_existing.append(fModel)
                try:
                    if len(files_existing) == 0:
                        raise NoFilesError('Maria Theresa')
                    file_to_transfer = files[int(fileCount)]
                    print '[Z]Attempting to transfer ' + str(file_to_transfer)
                    return_code = transfer_file(file_to_transfer)
                    if return_code != 0:
                        print 'USB unexpectedly removed!'
                        removeCorruptFile(file_to_transfer)
                except NoFilesError as error:
                    #Bug report: This thing is being thrown after downloading files? 
                    print 'Aiyappa file illa pa'
                    global optional_flag
                    if optional_flag:
                        usb_checked = attemptMount()
                        usb_flag = 'disabled'
                        text = 'Please insert USB and refresh   '
                        if usb_checked is not None:
                            usb_flag = 'active'
                            text = 'Click USB Download to download files'
                        return render(request, 'fileupload/ekfile_form.html', {'usb_checked': usb_flag, 'text':text})
                    template = loader.get_template('fileupload/downloadFiles.html')
                    total_files_in_db = EkFile.objects.all()
                    context = {
                        'files_existing' : None,
                        'show_output' : False,
                        'percentage_done' : 0,
                        'current_count' : 0,
                        'btn_check_flag' : 'disabled',
                        'download_more' : False,
                    }
                    return HttpResponse(template.render(context, request))
                '''
                except ValueError as error:
                    print 'Code should not come here ValueError'
                    fileCount = 0
                    file_to_transfer = files[int(fileCount)]
                    return_code = transfer_file(file_to_transfer)
                    if return_code != 0:
                        print 'USB unexpectedly removed!'
                        removeCorruptFile(file_to_transfer)
                    try:

file-upload/fileupload/templates/fileupload/LOGIN.html
<!DOCTYPE HTML>
<html>
<head>
<title>File Upload Login</title>
<link rel="stylesheet" href="../static/css/login.css">
<!img src="images.jpg" style="width:200px;right:200px;height:228px;margin:10px;">
</head>
<body>
<div class="login-page">
       <form  class="form" action="{% url 'fileupload:verify' %}" method="post">
    {%csrf_token%}
     {% if invalid %}
           <p>{{invalid}}</p>
     {% endif %}
      <input type="text" id="email" name="email" placeholder="username">
      <br>
      <input type="password" id="password" name="password" placeholder="password">
      <br>
     <Button type="submit">Login</Button>
    </form>
</div>
</body>
</html>

file-upload/fileupload/templates/fileupload/downloadFiles.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>Transfer USB Data</title>
<!-- All scripts go below this! -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="application/javascript"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" type="application/javascript"></script>
<!-- All scripts are above this! -->
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	</head>
	<body>
		<div class="container-fluid" align="center">
			<h1>USB File Transfer</h1>
		
		<div class="jumbotron">
			{% if files_existing %}
				<!-- Code to open a box and get the files here -->
				<p>Files being downloaded:
					{% for file in files_existing %}
						<p><b>{{ file.file }}: </b><!-- {{ file.file_desc }} --></p><br/>
					{% endfor  %}
				<form action='../return_USB/' method="post" name="InitUSB">
				{% csrf_token %}
					<!--input type="submit" value="Download Files" class = "btn btn-info {{ btn_check_flag }}" align="center"-->
					{% if show_output %}
					<!--{% for file in files_existing %} -->
					<form action='../transfer/' method="post" name="TransferFiles">
					{% csrf_token %}

						
							<input type="hidden" value="{{ current_count }}" name="file_descriptor">
							<p><script tyoe="application/javascript">
								document.TransferFiles.submit();
							</script></p>
						<div class = "progress">
							<div class = "progress-bar progress-bar-striped active" role="progressbar" aria-valuenow = "{{ percentage_done }}" aria-valuemin = "0" aria-valuemax="100"
									style = "width:{{ percentage_done }}%">{{ percentage_done }}%
							</div>
						</div>
						

					</form>
					<!--{% endfor %}-->
					{% endif %}
				</form>
				{% if download_more %}
						{% else %}
							<p>All Files have been transferred to the Raspberry Pi</p>
						{% endif %}
			{% else %}
				<!-- Code to tell the user to come back later here -->
				<p algin="center">No new files are available through the USB. Insert new USB and refresh.<p>
			{% endif %}
		</div>
		</div>
	</body>
</html>

file-upload/fileupload/templates/fileupload/ekfile_form.html
{% extends "upload_base.html" %}
{% load upload_tags %}

{% block content %}
<input type="hidden" id="refresh" value="no">
<div class="container">
    <h1 id="h">File Upload</h1><br/>
    <div class="jumbotron">{{ text }}</div>
    <br>
    <!-- The file upload form used as target for the file upload widget -->
    <form id="fileupload" method="post" action="." enctype="multipart/form-data">{% csrf_token %}
        
        <div class="row fileupload-buttonbar">
            <div class="col-lg-7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="file" multiple>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start upload</span>
                </button>
                <button type="button" class="btn btn-primay start {{ usb_checked }}" id="usb">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>USB upload</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel upload</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" class="toggle">
                <!-- The loading indicator is shown during file processing -->
                <span class="fileupload-loading"></span>
            </div>
            <!-- The global progress information -->
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress information -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
    </form>
    <br>
    
</div>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
{% upload_js %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="/static/js/ajax-utils.js"></script>
<script src="/static/js/scripts.js"></script>
<script src="jquery-3.2.1.min.js"></script>

<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/static/js/vendor/jquery.ui.widget.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="/static/js/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="/static/js/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="/static/js/canvas-to-blob.min.js"></script>
<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
<script src="/static/js/bootstrap.min.js"></script>
<!-- blueimp Gallery script -->
<script src="/static/js/jquery.blueimp-gallery.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/static/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/static/js/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="/static/js/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="/static/js/jquery.fileupload-image.js"></script>
<!-- The File Upload audio preview plugin -->
<script src="/static/js/jquery.fileupload-audio.js"></script>
<!-- The File Upload video preview plugin -->
<script src="/static/js/jquery.fileupload-video.js"></script>
<!-- The File Upload validation plugin -->
<script src="/static/js/jquery.fileupload-validate.js"></script>
<!-- The File Upload user interface plugin -->
<script src="/static/js/jquery.fileupload-ui.js"></script>
<!-- The main application script -->
<script src="/static/js/main.js"></script>
<script src="/static/js/locale.js"></script>
<script src="/static/js/csrf.js"></script>

{% endblock %}